services:
  navy_manager_db:
    restart: always
    image: postgres:14.3-alpine
    container_name: navy_manager_db
    environment:
      POSTGRES_DB: navy_manager_db
      POSTGRES_USER: navy_manager_user
      POSTGRES_PASSWORD: fleetingimage
    ports:
      - "5433:5432"

  navy_manager_app:
    image: navy_manager_app
    build:
      context: .
    container_name: navy_manager_app
    depends_on:
      - navy_manager_db
    environment:
      - DB_HOST=navy_manager_db
      - DB_PORT=5432
      - DB_NAME=navy_manager_db
      - DB_USER=navy_manager_user
      - DB_PASSWORD=fleetingimage
    ports:
      - "8080:8080"